apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: afdff699618424fc89f2b040b544b688-754960151.us-west-1.elb.amazonaws.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: student-app-frontend-svc
              port: 
                number: 80 
         

